listenPort: 3000
bindAddress: 0.0.0.0

networks:
  - name: "Network 1" #Name of Network. This is only used locally
    url: "https://network1.com" #Url you would use to access the whackerlink network
    token: "" #JWT given by the network admin

  - name: "Network 2"
    url: "https://network2.net:5000"
    token: ""