# Disabled location broadcasts logging
disableLocationBcast: true
# Disable reports showing location broadcasts
disableLocationBcastReports: true
# Disable site broadcast logging and reports
disableSiteBcast: false

# Port to bind the server to
listenPort: 3001
# Address to bind the server to
bindAddress: 127.0.0.1

# List of networks to connect to
networks:
    # Textual alias for the network
  - name: "Dev Master 1"
    # URL to connect to (REST)
    url: "http://127.0.0.1:3002"
    # Port to listen for reports
    listenPort: 3000
    # Address to listen for reports
    bindAddress: 127.0.0.1

  # Textual alias for the network
  - name: "Example Master 2"
    # URL to connect to (REST)
    url: "http://127.0.0.1:3003"
    # Port to listen for reports
    listenPort: 3004
    # Address to listen for reports
    bindAddress: 127.0.0.1