# Disabled location broadcasts logging
disableLocationBcast: true
# Disable reports showing location broadcasts
disableLocationBcastReports: true
# Disable site broadcast logging and reports
disableSiteBcast: false

# Port to bind the server to
listenPort: 3001
# Address to bind the server to
bindAddress: 127.0.0.1

restServers:
    # Textual alias for the REST server (internal use)
  - name: "Dev Server 1"
    # URL to connect to (REST)
    url: "http://127.0.0.1:3002"
    # Password for the REST server
    password: "PASSWORD"

# List of networks to connect to
networks:
    # Textual alias for the network
  - name: "Dev Master"
    # Internal name of the REST server for this Master
    restServer: "Dev Server 1"
    # Port to listen for reports
    listenPort: 3005
    # Address to listen for reports
    bindAddress: 127.0.0.1

#    # Textual alias for the network
#  - name: "Example Master 2"
#    # Internal name of the REST server for this Master
#    restServer: "Dev Server 1"
#    # Port to listen for reports
#    listenPort: 3006
#    # Address to listen for reports
#    bindAddress: 127.0.0.1